# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

# trigger:
# - master
# - develop

pool:
  vmImage: 'macOS-10.14'

steps:
- task: CocoaPods@0
  inputs:
    forceRepoUpdate: true
  displayName: 'pod install using the CocoaPods task with defaults'

- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'DistCertificate.p12'
    certPwd: "admin123"
  condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/develop'))

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'nCashDist.mobileprovision'
    removeProfile: true # Optional
  condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/develop'))

- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'UniversalLinks'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/UniversalLinks.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath

- task: Xcode@5
  inputs:
    actions: 'archive'
    scheme: 'UniversalLinks'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/UniversalLinks.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
    packageApp: true
    archivePath: '$(system.defaultworkingdirectory)/build/UniversalLinks.xcarchive'
    exportPath: '$(system.defaultworkingdirectory)/build'
    # exportPath: 'output/$(SDK)/Release' # Optional
    exportOptions: 'plist'
    # exportMethod: 'development' # Required when exportOptions == Specify
    # exportTeamId: 'U98KTBTAC9'
    exportOptionsPlist: '$(system.defaultworkingdirectory)/ExportOptions.plist'
    # exportPath: '$(system.defaultworkingdirectory)'
    # signingOption: 'manual' # Options: nosign, default, manual, auto
    signingOption: 'manual'
    provisioningProfileUuid: 'com.nihilentmobile.ncash'
    provisioningProfileName: 'nCashDist'
    # teamId: 'U98KTBTAC9'
    useXcpretty: true # Makes it easier to diagnose build failures
  condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/develop'))

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '/**/*.ipa'
    TargetFolder: '$(build.artifactStagingDirectory)'
  condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/develop'))

- task: PublishBuildArtifacts@1
  condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/develop'))


# App Center distribute - 'develop' branch
# Distribute app builds to testers and users via Visual Studio App Center
- task: AppCenterDistribute@1
  inputs:
    serverEndpoint: 'AppCenterConnection'
    # appSlug: '{APPCENTER_USERNAME}/{APPCENTER_APPID}'
    appSlug: 'preetam.jadakar/nCash'
    appFile: '$(build.artifactStagingDirectory)/**/*.ipa'
    symbolsOption: 'Apple' # Optional. Options: apple
    #symbolsPath: # Optional
    #symbolsPdbFiles: '**/*.pdb' # Optional
    #symbolsDsymFiles: # Optional
    #symbolsMappingTxtFile: # Optional
    #symbolsIncludeParentDirectory: # Optional
    releaseNotesOption: 'file' #'input'
    # releaseNotesInput: 'Implemented build auto-increment using shell scrpts.'
    releaseNotesFile: '$(system.defaultworkingdirectory)/ReleaseNotes'
    #isMandatory: false # Optional
    distributionGroupId: '057661c4-02ef-4955-826a-3397cf7445e6'
    destinationType: 'groups'
    useXcpretty: true # Makes it easier to diagnose build failures
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))

# App Center distribute - 'master' branch
# Distribute app builds to testers and users via Visual Studio App Center
- task: AppCenterDistribute@1
  inputs:
    serverEndpoint: 'AppCenterConnection'
    # appSlug: '{APPCENTER_USERNAME}/{APPCENTER_APPID}'
    appSlug: 'preetam.jadakar/nCash'
    appFile: '$(build.artifactStagingDirectory)/**/*.ipa'
    symbolsOption: 'Apple' # Optional. Options: apple
    #symbolsPath: # Optional
    #symbolsPdbFiles: '**/*.pdb' # Optional
    #symbolsDsymFiles: # Optional
    #symbolsMappingTxtFile: # Optional
    #symbolsIncludeParentDirectory: # Optional
    releaseNotesOption: 'file' #'input'
    # releaseNotesInput: 'Implemented build auto-increment using shell scrpts.'
    releaseNotesFile: '$(system.defaultworkingdirectory)/ReleaseNotes'
    #isMandatory: false # Optional
    distributionGroupId: 'e018552d-68ff-466b-bb08-4fb12050da8b'
    destinationType: 'groups'
    useXcpretty: true # Makes it easier to diagnose build failures
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

